### ISSUE TITLE
Suggestion: Body centering (with code suggestion)

### ISSUE THREAD

**Issue by Offirmo** [mozilla-devoutreach/cssremedy#92]
Hi and thanks for the lib!

While admittedly not 100% semantic, centering the body and constraining its width is a top-rated improvement in readability. Since html is all about documents, I feel it's acceptable and welcome. 

References:

- #1 most important styling according to https://jgthms.com/web-design-in-4-minutes/#centering
- top rated as well on https://www.robinrendle.com/notes/the-smallest-css/

Here is my suggestion (public domain), which uses modern CSS features and takes into account small and big screens:

```css
body {
	--content-recommended-width: 65ch;
	/* max width + centering = #1 most important styling according to https://jgthms.com/web-design-in-4-minutes/#centering
	 */
	max-width: var(--content-recommended-width);
	margin: 0 max(1ch, (100vw - var(--content-recommended-width))/2); /* intelligent centering with a minimum margin for small screens */
	/* no padding needed since space is provided by this various margins:
	 * vertical: blocks have their own margin, ex. headers, paragraphs...
	 * horizontal: not needed thanks to to the intelligent centering above featuring a minimum margin
	 * see also https://www.miriamsuzanne.com/2022/07/04/body-margin-8px/
	 */
	padding: 0;
}
```

P.S. thanks @mirisuzanne for bringing me here through https://www.miriamsuzanne.com/2022/07/04/body-margin-8px/
